name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  buildAndTest:
    name: Build And Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install Dependencies
        run: python -m pip install .[dev]

      - name: Validate Code
        run: |
          python -m pylint -E ./discord/ext/prometheus/
          python -m pylint -E ./tests/
          
      - name: Tests
        run: python -m unittest discover -v -s ./tests -p test_*.py
        continue-on-error: true

      - name: Check Formatting
        run: python -m black --check ./discord/ext/prometheus/
