name: Python

on:
  push:
    branches: ['main']
    paths-ignore:
      - './README.md'

jobs:

  build:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: python -m pip install -r ./requirements.txt

      - name: Validate Code
        run: |
          python -m pylint -E ./discord/ext/prometheus/
          python -m pylint -E ./tests/

      - name: Tests
        run: python -m unittest discover -v -s ./tests -p test_*.py

  upload:
    needs: [ build ]
    name: Upload Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Dependencies
        run: python -m pip install build twine

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        run: |
          python -m twine upload ./dist/* \
            --username __token__ \
            --password ${{ secrets.PYPI_API_TOKEN }}
